services:
  final-project:
    # Use the image from ECR instead of building locally
    image: ${ECR_URL}:${IMAGE_TAG} 
    container_name: final-project
    ports:
      - "8080:80"
    environment:
      - USER_NAME=${USER_NAME:-DevOps Engineer}
    restart: unless-stopped
